# http_path = "/"
css_dir = "."
sass_dir = "./sass"
images_dir = "images"
fonts_dir = "./fonts"
javascripts_dir = "./js"
output_style = :compressed
relative_assets=true
line_comments = false
http_generated_images_path = "./images"